### ISSUE TITLE
unable to invoke the shareFile method

### ISSUE THREAD

**Issue by yuenweikdu** [alfianlosari/flutter_qr_code_scanner_generator_sharing#1]
E/flutter (14539): MissingPluginException(No implementation found for method shareFile on channel channel:me.alfian.share/share)

Hi, this error appeared when I tried to share the image of QR code.May i know is it any additional plugins or code required? btw, thanks so much for writing the Medium article. Really appreciate it. Hope you will notice this issue.

**Comment by fllaryora** [comment]
I'm having the same issue in flutter.
some body coud get a simple solution?

**Comment by ad-nagdeve28** [comment]
Same error getting
